import { table, autoGeneratedHashKey, attribute } from "@aws/dynamodb-data-mapper-annotations";

@table("wn_message")
export class MessageModel {
    @autoGeneratedHashKey() id: string;
    @attribute() title:string;
    @attribute() description:string;
    @attribute() link:string;
    @attribute() to:string;
    @attribute() saidBy: string;
    @attribute() createdAt: Date;
    @attribute() keywords: string; 
  }
  