import {
  attribute,
  autoGeneratedHashKey,
  rangeKey,
  table,
  versionAttribute
} from "@aws/dynamodb-data-mapper-annotations";

@table("wn_user")
export class UserModel {
  @autoGeneratedHashKey() id: string;

  @attribute() email: string;

  @attribute() password: string;

  @attribute() displayName: string;

  @attribute() imageUrl: string;

  @attribute() type: string;

  @attribute() activateCode: string;

  @attribute() status: string;

  @attribute() createdAt: Date;

  @attribute() searchText: string;
}
