import {
  attribute,
  autoGeneratedHashKey,
  rangeKey,
  table,
  versionAttribute,
  hashKey
} from "@aws/dynamodb-data-mapper-annotations";

import { JsonObject, JsonProperty } from 'json2typescript';

@table("wn_user")
export class UserModel {
  @autoGeneratedHashKey()   
  @hashKey()
  @JsonProperty('id', String)
  id: string;

  @rangeKey()
  @attribute() email: string;

  @attribute() password: string;

  @attribute() displayName: string;

  @attribute() imageUrl: string;

  @attribute() type: string;

  @attribute() activateCode: string;

  @attribute() status: string;

  @attribute() createdAt: Date;

  @attribute() searchText: string;
}
